name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Deploy _site folder to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv _site/* .
          rm -R _site/
          git add -A
          git commit -m "Deploy _site to GitHub Pages"
          git push -u origin gh-pages --force
